blank_issues_enabled: true
contact_links:
  - name: 提交 Snap Hutao Manjusaka 客户端问题报告 / Submit Snap Hutao Manjusaka Client Issues
    url: https://github.com/hoshiizumiya/Snap.Hutao-Manjusaka/issues/new
    about: 客户端问题请点击此处跳转至主库提交 / Please click here to redirect to main repository for client issues
